import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createNotification } from '@/lib/notifications';

// GET /api/visits - List user's visits (as visitor or owner)
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const searchParams = request.nextUrl.searchParams;
    const role = searchParams.get('role') || 'all'; // 'visitor', 'owner', or 'all'
    const status = searchParams.get('status'); // Filter by status

    let query = supabase
      .from('pricewaze_visits')
      .select(`
        *,
        property:pricewaze_properties(id, title, address, images),
        visitor:pricewaze_profiles!visitor_id(id, full_name, email, avatar_url),
        owner:pricewaze_profiles!owner_id(id, full_name, email, avatar_url)
      `)
      .order('scheduled_at', { ascending: true });

    // Filter by role
    if (role === 'visitor') {
      query = query.eq('visitor_id', user.id);
    } else if (role === 'owner') {
      query = query.eq('owner_id', user.id);
    } else {
      query = query.or(`visitor_id.eq.${user.id},owner_id.eq.${user.id}`);
    }

    // Filter by status
    if (status) {
      query = query.eq('status', status);
    }

    const { data: visits, error } = await query;

    if (error) {
      console.error('Error fetching visits:', error);
      return NextResponse.json({ error: 'Failed to fetch visits' }, { status: 500 });
    }

    return NextResponse.json(visits);
  } catch (error) {
    console.error('Visits GET error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// POST /api/visits - Schedule a new visit
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { property_id, scheduled_at, notes } = body;

    if (!property_id || !scheduled_at) {
      return NextResponse.json(
        { error: 'Property ID and scheduled date are required' },
        { status: 400 }
      );
    }

    // Get the property to find the owner
    const { data: property, error: propertyError } = await supabase
      .from('pricewaze_properties')
      .select('id, owner_id, title')
      .eq('id', property_id)
      .single();

    if (propertyError || !property) {
      return NextResponse.json({ error: 'Property not found' }, { status: 404 });
    }

    // Cannot schedule visit for own property
    if (property.owner_id === user.id) {
      return NextResponse.json(
        { error: 'Cannot schedule a visit for your own property' },
        { status: 400 }
      );
    }

    // Check for existing pending/scheduled visit
    const { data: existingVisit } = await supabase
      .from('pricewaze_visits')
      .select('id')
      .eq('property_id', property_id)
      .eq('visitor_id', user.id)
      .in('status', ['scheduled'])
      .single();

    if (existingVisit) {
      return NextResponse.json(
        { error: 'You already have a scheduled visit for this property' },
        { status: 400 }
      );
    }

    // Create the visit (verification_code is auto-generated by DB)
    const { data: visit, error: createError } = await supabase
      .from('pricewaze_visits')
      .insert({
        property_id,
        visitor_id: user.id,
        owner_id: property.owner_id,
        scheduled_at: new Date(scheduled_at).toISOString(),
        notes,
      })
      .select(`
        *,
        property:pricewaze_properties(id, title, address, images),
        visitor:pricewaze_profiles!visitor_id(id, full_name, email),
        owner:pricewaze_profiles!owner_id(id, full_name, email)
      `)
      .single();

    if (createError) {
      console.error('Error creating visit:', createError);
      return NextResponse.json({ error: 'Failed to schedule visit' }, { status: 500 });
    }

    // Send notification to property owner
    if (property.owner_id) {
      await createNotification(supabase, {
        user_id: property.owner_id,
        title: 'New Visit Request',
        message: `${visit.visitor?.full_name || 'A visitor'} requested to visit ${property.title}`,
        type: 'visit_requested',
        data: {
          visit_id: visit.id,
          property_id: property_id,
          scheduled_at: scheduled_at,
        },
      });
    }

    return NextResponse.json(visit, { status: 201 });
  } catch (error) {
    console.error('Visits POST error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
