import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createNotification } from '@/lib/notifications';
import { z } from 'zod';
import { Errors, ErrorCodes, apiError } from '@/lib/api/errors';

// Zod schema for scheduling visits
const createVisitSchema = z.object({
  property_id: z.string().uuid('Invalid property ID format'),
  scheduled_at: z.string()
    .refine((val) => !isNaN(Date.parse(val)), 'Invalid date format')
    .refine((val) => new Date(val) > new Date(), 'Visit must be scheduled in the future'),
  notes: z.string().max(1000, 'Notes must be less than 1000 characters').optional(),
});

// GET /api/visits - List user's visits (as visitor or owner)
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return Errors.unauthorized();
    }

    const searchParams = request.nextUrl.searchParams;
    const role = searchParams.get('role') || 'all'; // 'visitor', 'owner', or 'all'
    const status = searchParams.get('status'); // Filter by status

    let query = supabase
      .from('pricewaze_visits')
      .select(`
        *,
        property:pricewaze_properties(id, title, address, images),
        visitor:pricewaze_profiles!visitor_id(id, full_name, email, avatar_url),
        owner:pricewaze_profiles!owner_id(id, full_name, email, avatar_url)
      `)
      .order('scheduled_at', { ascending: true });

    // Filter by role
    if (role === 'visitor') {
      query = query.eq('visitor_id', user.id);
    } else if (role === 'owner') {
      query = query.eq('owner_id', user.id);
    } else {
      query = query.or(`visitor_id.eq.${user.id},owner_id.eq.${user.id}`);
    }

    // Filter by status
    if (status) {
      query = query.eq('status', status);
    }

    const { data: visits, error } = await query;

    if (error) {
      console.error('Error fetching visits:', error);
      return apiError('Failed to fetch visits', ErrorCodes.SYS_002, 500);
    }

    return NextResponse.json(visits || []);
  } catch (error) {
    console.error('Visits GET error:', error);
    return Errors.serverError();
  }
}

// POST /api/visits - Schedule a new visit
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return Errors.unauthorized();
    }

    const body = await request.json();

    // Validate input with Zod
    const parseResult = createVisitSchema.safeParse(body);
    if (!parseResult.success) {
      return Errors.validationFailed(parseResult.error.flatten().fieldErrors as Record<string, unknown>);
    }

    const { property_id, scheduled_at, notes } = parseResult.data;

    // Get the property to find the owner
    const { data: property, error: propertyError } = await supabase
      .from('pricewaze_properties')
      .select('id, owner_id, title')
      .eq('id', property_id)
      .single();

    if (propertyError || !property) {
      return Errors.notFound('Property');
    }

    // Cannot schedule visit for own property
    if (property.owner_id === user.id) {
      return apiError('Cannot schedule a visit for your own property', ErrorCodes.VISIT_004, 400);
    }

    // Check for existing pending/scheduled visit
    const { data: existingVisit } = await supabase
      .from('pricewaze_visits')
      .select('id')
      .eq('property_id', property_id)
      .eq('visitor_id', user.id)
      .in('status', ['scheduled'])
      .single();

    if (existingVisit) {
      return apiError('You already have a scheduled visit for this property', ErrorCodes.VISIT_003, 409);
    }

    // Create the visit (verification_code is auto-generated by DB)
    const { data: visit, error: createError } = await supabase
      .from('pricewaze_visits')
      .insert({
        property_id,
        visitor_id: user.id,
        owner_id: property.owner_id,
        scheduled_at: new Date(scheduled_at).toISOString(),
        notes,
      })
      .select(`
        *,
        property:pricewaze_properties(id, title, address, images),
        visitor:pricewaze_profiles!visitor_id(id, full_name, email),
        owner:pricewaze_profiles!owner_id(id, full_name, email)
      `)
      .single();

    if (createError) {
      console.error('Error creating visit:', createError);
      return apiError('Failed to schedule visit', ErrorCodes.SYS_002, 500);
    }

    // Send notification to property owner
    if (property.owner_id) {
      await createNotification(supabase, {
        user_id: property.owner_id,
        title: 'New Visit Request',
        message: `${visit.visitor?.full_name || 'A visitor'} requested to visit ${property.title}`,
        type: 'visit_requested',
        data: {
          visit_id: visit.id,
          property_id: property_id,
          scheduled_at: scheduled_at,
        },
      });
    }

    return NextResponse.json(visit, { status: 201 });
  } catch (error) {
    console.error('Visits POST error:', error);
    return Errors.serverError();
  }
}
