"""Contract generation tools for CrewAI agents."""

from datetime import datetime, timedelta
from typing import Any

from crewai.tools import BaseTool
from pydantic import BaseModel, Field


LEGAL_DISCLAIMER = """
AVISO LEGAL / LEGAL DISCLAIMER

Este documento es un BORRADOR NO VINCULANTE generado por inteligencia artificial con fines informativos y de referencia únicamente. NO constituye un contrato legal válido y NO debe ser utilizado como documento final para ninguna transacción inmobiliaria.

This document is a NON-BINDING DRAFT generated by artificial intelligence for informational and reference purposes only. It does NOT constitute a valid legal contract and should NOT be used as a final document for any real estate transaction.

ANTES DE PROCEDER CON CUALQUIER TRANSACCIÓN INMOBILIARIA:
1. Consulte con un abogado licenciado en la República Dominicana
2. Verifique todos los registros de propiedad con el Registro de Títulos
3. Realice la debida diligencia sobre el inmueble y las partes involucradas
4. Obtenga un contrato formal preparado por profesionales legales

BEFORE PROCEEDING WITH ANY REAL ESTATE TRANSACTION:
1. Consult with a licensed attorney in the Dominican Republic
2. Verify all property records with the Registro de Títulos
3. Conduct due diligence on the property and parties involved
4. Obtain a formal contract prepared by legal professionals

PriceWaze no asume responsabilidad alguna por el uso de este documento.
PriceWaze assumes no liability for the use of this document.
""".strip()


class ContractParty(BaseModel):
    """Schema for a contract party."""

    name: str = Field(description="Full legal name")
    email: str | None = Field(default=None, description="Email address")
    id_number: str | None = Field(default=None, description="Cédula or passport number")


class PropertyDetails(BaseModel):
    """Schema for property details in contract."""

    address: str = Field(description="Full property address")
    description: str = Field(description="Property description")
    area_m2: float | None = Field(default=None, description="Property area in m²")
    registry_number: str | None = Field(default=None, description="Registry number if known")


class GenerateContractTemplateInput(BaseModel):
    """Input schema for contract generation."""

    buyer: ContractParty = Field(description="Buyer information")
    seller: ContractParty = Field(description="Seller information")
    property_details: PropertyDetails = Field(description="Property information")
    agreed_price: float = Field(description="Agreed sale price in USD")
    deposit_percent: float = Field(default=10, description="Deposit percentage")
    closing_days: int = Field(default=30, description="Days until closing")
    special_conditions: list[str] | None = Field(default=None, description="Special conditions")


class GenerateContractTemplateTool(BaseTool):
    """Generate a draft purchase agreement template."""

    name: str = "generate_contract_template"
    description: str = (
        "Generates a bilingual (Spanish/English) draft purchase agreement for "
        "Dominican Republic real estate transactions. Includes standard terms, "
        "payment schedule, and legal disclaimers. NOT a final legal document."
    )
    args_schema: type[BaseModel] = GenerateContractTemplateInput

    def _run(
        self,
        buyer: ContractParty,
        seller: ContractParty,
        property_details: PropertyDetails,
        agreed_price: float,
        deposit_percent: float = 10,
        closing_days: int = 30,
        special_conditions: list[str] | None = None,
    ) -> dict[str, Any]:
        """Generate contract template."""
        today = datetime.now()
        closing_date = today + timedelta(days=closing_days)

        deposit_amount = agreed_price * (deposit_percent / 100)
        balance_amount = agreed_price - deposit_amount

        # Format dates
        today_str = today.strftime("%d de %B de %Y")
        closing_str = closing_date.strftime("%d de %B de %Y")

        # Build contract content
        contract = f"""
═══════════════════════════════════════════════════════════════════════════════
                      BORRADOR DE CONTRATO DE COMPRAVENTA
                         DRAFT PURCHASE AGREEMENT
═══════════════════════════════════════════════════════════════════════════════

                        ⚠️ DOCUMENTO NO VINCULANTE ⚠️
                        ⚠️ NON-BINDING DOCUMENT ⚠️

Fecha / Date: {today_str}
Referencia / Reference: PWZ-{today.strftime('%Y%m%d')}-{hash(buyer.name) % 10000:04d}

───────────────────────────────────────────────────────────────────────────────
                              PARTES / PARTIES
───────────────────────────────────────────────────────────────────────────────

VENDEDOR / SELLER:
Nombre / Name: {seller.name}
Cédula / ID: {seller.id_number or '[________________________]'}
Correo / Email: {seller.email or '[________________________]'}
Domicilio / Address: [________________________]

COMPRADOR / BUYER:
Nombre / Name: {buyer.name}
Cédula / ID: {buyer.id_number or '[________________________]'}
Correo / Email: {buyer.email or '[________________________]'}
Domicilio / Address: [________________________]

───────────────────────────────────────────────────────────────────────────────
                         DESCRIPCIÓN DEL INMUEBLE
                         PROPERTY DESCRIPTION
───────────────────────────────────────────────────────────────────────────────

Dirección / Address: {property_details.address}
Descripción / Description: {property_details.description}
Área / Area: {f'{property_details.area_m2} m²' if property_details.area_m2 else '[A verificar / To be verified]'}
Número de Registro / Registry Number: {property_details.registry_number or '[________________________]'}

───────────────────────────────────────────────────────────────────────────────
                         TÉRMINOS DE LA TRANSACCIÓN
                         TRANSACTION TERMS
───────────────────────────────────────────────────────────────────────────────

PRECIO ACORDADO / AGREED PRICE:
${agreed_price:,.2f} USD (Dólares de los Estados Unidos de América)

FORMA DE PAGO / PAYMENT TERMS:

1. Depósito inicial / Initial Deposit: ${deposit_amount:,.2f} USD ({deposit_percent}%)
   - Pagadero a la firma de este acuerdo preliminar
   - Payable upon signing of this preliminary agreement

2. Balance / Balance: ${balance_amount:,.2f} USD ({100 - deposit_percent}%)
   - Pagadero al cierre de la transacción
   - Payable at closing

FECHA ESTIMADA DE CIERRE / ESTIMATED CLOSING DATE:
{closing_str} ({closing_days} días desde la firma / days from signing)

───────────────────────────────────────────────────────────────────────────────
                              CONDICIONES
                              CONDITIONS
───────────────────────────────────────────────────────────────────────────────

CONDICIONES ESTÁNDAR / STANDARD CONDITIONS:

1. El vendedor garantiza que el inmueble está libre de gravámenes,
   hipotecas y cualquier otro tipo de carga.
   The seller guarantees the property is free of liens, mortgages,
   and any other encumbrances.

2. El comprador tendrá derecho a realizar una inspección del
   inmueble antes del cierre.
   The buyer shall have the right to inspect the property
   before closing.

3. Ambas partes se comprometen a formalizar la venta ante notario
   público dentro del plazo establecido.
   Both parties agree to formalize the sale before a notary
   public within the established timeframe.

4. La transferencia de título se realizará ante el Registro de
   Títulos correspondiente.
   Title transfer shall be completed at the corresponding
   Title Registry Office.

5. Los gastos notariales y de registro serán cubiertos según la
   legislación dominicana vigente (tradicionalmente 50/50).
   Notarial and registry fees shall be covered according to
   Dominican law (traditionally 50/50).
"""

        # Add special conditions if any
        if special_conditions:
            contract += """
CONDICIONES ESPECIALES / SPECIAL CONDITIONS:
"""
            for i, condition in enumerate(special_conditions, 1):
                contract += f"\n{i}. {condition}\n"

        contract += f"""
───────────────────────────────────────────────────────────────────────────────
                               FIRMAS
                             SIGNATURES
───────────────────────────────────────────────────────────────────────────────

VENDEDOR / SELLER:

_________________________________
{seller.name}
Fecha / Date: ___________________


COMPRADOR / BUYER:

_________________________________
{buyer.name}
Fecha / Date: ___________________


TESTIGO / WITNESS:

_________________________________
Nombre / Name: ___________________
Cédula / ID: _____________________

═══════════════════════════════════════════════════════════════════════════════
                    Generado por PriceWaze / Generated by PriceWaze
                           {today.strftime('%Y-%m-%d %H:%M:%S')}
═══════════════════════════════════════════════════════════════════════════════

{LEGAL_DISCLAIMER}
"""

        return {
            "success": True,
            "contract": {
                "content": contract.strip(),
                "parties": {
                    "buyer": buyer.model_dump(),
                    "seller": seller.model_dump(),
                },
                "property": property_details.model_dump(),
                "terms": {
                    "agreed_price": agreed_price,
                    "currency": "USD",
                    "deposit_amount": deposit_amount,
                    "deposit_percent": deposit_percent,
                    "balance_amount": balance_amount,
                    "closing_date": closing_str,
                    "closing_days": closing_days,
                },
                "generated_at": today.isoformat(),
                "disclaimer": LEGAL_DISCLAIMER,
            },
        }


class ValidateContractTermsInput(BaseModel):
    """Input schema for contract terms validation."""

    agreed_price: float = Field(description="Agreed sale price")
    property_price: float = Field(description="Original listing price")
    deposit_percent: float = Field(description="Deposit percentage")
    closing_days: int = Field(description="Days until closing")


class ValidateContractTermsTool(BaseTool):
    """Validate contract terms against market standards."""

    name: str = "validate_contract_terms"
    description: str = (
        "Validates proposed contract terms against Dominican Republic real estate "
        "market standards and identifies potential issues or unusual terms."
    )
    args_schema: type[BaseModel] = ValidateContractTermsInput

    def _run(
        self,
        agreed_price: float,
        property_price: float,
        deposit_percent: float,
        closing_days: int,
    ) -> dict[str, Any]:
        """Validate contract terms."""
        issues = []
        warnings = []
        valid = True

        # Price validation
        discount_percent = ((property_price - agreed_price) / property_price) * 100
        if discount_percent > 25:
            warnings.append({
                "field": "agreed_price",
                "message": f"Price is {discount_percent:.1f}% below listing - unusually high discount",
                "recommendation": "Verify seller acceptance and property condition",
            })
        elif discount_percent < 0:
            warnings.append({
                "field": "agreed_price",
                "message": "Agreed price is above listing price",
                "recommendation": "Verify this is intentional (e.g., multiple offers)",
            })

        # Deposit validation
        if deposit_percent < 5:
            issues.append({
                "field": "deposit_percent",
                "message": "Deposit below 5% may not be accepted by seller",
                "recommendation": "Standard deposit in DR is 10-20%",
            })
            valid = False
        elif deposit_percent > 30:
            warnings.append({
                "field": "deposit_percent",
                "message": f"Deposit of {deposit_percent}% is above typical range",
                "recommendation": "Consider reducing to standard 10-20%",
            })

        # Closing timeline validation
        if closing_days < 14:
            warnings.append({
                "field": "closing_days",
                "message": "Closing in less than 14 days may not allow proper due diligence",
                "recommendation": "Consider extending to 30-45 days minimum",
            })
        elif closing_days > 90:
            warnings.append({
                "field": "closing_days",
                "message": "Closing timeline over 90 days is unusually long",
                "recommendation": "Seller may request shorter timeline",
            })

        return {
            "success": True,
            "validation": {
                "is_valid": valid and len(issues) == 0,
                "issues": issues,
                "warnings": warnings,
                "summary": {
                    "agreed_price": agreed_price,
                    "discount_from_listing": f"{discount_percent:.1f}%",
                    "deposit_amount": agreed_price * (deposit_percent / 100),
                    "deposit_percent": deposit_percent,
                    "closing_days": closing_days,
                    "meets_standards": len(issues) == 0,
                },
            },
        }
