import OpenAI from 'openai';
import type { ContractDraft } from '@/types/pricing';
import { getMarketConfig, formatPrice } from '@/config/market';

// Lazy-load client to avoid build-time errors
let deepseek: OpenAI | null = null;

function getClient(): OpenAI {
  if (!deepseek) {
    deepseek = new OpenAI({
      apiKey: process.env.DEEPSEEK_API_KEY,
      baseURL: process.env.DEEPSEEK_BASE_URL || 'https://api.deepseek.com',
    });
  }
  return deepseek;
}

const MODEL = process.env.DEEPSEEK_MODEL || 'deepseek-chat';

function getLegalDisclaimer(): string {
  const market = getMarketConfig();

  return `
AVISO LEGAL / LEGAL DISCLAIMER

Este documento es un BORRADOR NO VINCULANTE generado por inteligencia artificial con fines informativos y de referencia únicamente. NO constituye un contrato legal válido y NO debe ser utilizado como documento final para ninguna transacción inmobiliaria.

This document is a NON-BINDING DRAFT generated by artificial intelligence for informational and reference purposes only. It does NOT constitute a valid legal contract and should NOT be used as a final document for any real estate transaction.

ANTES DE PROCEDER CON CUALQUIER TRANSACCIÓN INMOBILIARIA:
1. ${market.legal.disclaimerEs}
2. Verifique todos los registros de propiedad con las autoridades correspondientes
3. Realice la debida diligencia sobre el inmueble y las partes involucradas
4. Obtenga un contrato formal preparado por profesionales legales

BEFORE PROCEEDING WITH ANY REAL ESTATE TRANSACTION:
1. ${market.legal.disclaimerEn}
2. Verify all property records with the appropriate registry
3. Conduct due diligence on the property and parties involved
4. Obtain a formal contract prepared by legal professionals

PriceMap / PriceWaze no asume responsabilidad alguna por el uso de este documento.
PriceMap / PriceWaze assumes no liability for the use of this document.
`.trim();
}

interface ContractInput {
  offerId: string;
  buyer: {
    id: string;
    full_name: string;
    email?: string;
  };
  seller: {
    id: string;
    full_name: string;
    email?: string;
  };
  property: {
    id: string;
    title: string;
    address: string;
    description?: string;
    area_m2?: number;
    property_type: string;
  };
  agreedPrice: number;
  offerMessage?: string;
}

export async function generateContractDraft(input: ContractInput): Promise<ContractDraft> {
  const market = getMarketConfig();

  const prompt = `You are a legal document assistant specializing in ${market.ai.marketContext}. Generate a DRAFT purchase agreement (Contrato de Compraventa) based on the following information.

IMPORTANT: This is a NON-BINDING draft for reference only. Include clear language stating this is not a final legal document.

TRANSACTION DETAILS:
- Buyer: ${input.buyer.full_name}
- Seller: ${input.seller.full_name}
- Property: ${input.property.title}
- Address: ${input.property.address}
- Property Type: ${input.property.property_type}
- Area: ${input.property.area_m2 ? `${input.property.area_m2} m²` : 'To be verified'}
- Agreed Price: ${formatPrice(input.agreedPrice, market)}
- Notes from negotiation: ${input.offerMessage || 'None'}

Generate a bilingual (Spanish/English) draft contract that includes:
1. Identification of parties (with placeholders for ID numbers)
2. Property description (with placeholder for registry number)
3. Agreed price and payment terms (standard 10% deposit, balance at closing)
4. Standard conditions (clear title, no liens, property inspection)
5. Closing timeline (suggest 30-45 days)
6. Signatures section

Write the contract in formal legal Spanish with English translations for key sections.
Format it professionally with proper headings and numbered clauses.`;

  try {
    const response = await getClient().chat.completions.create({
      model: MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.2,
      max_tokens: 3000,
    });

    const contractContent = response.choices[0]?.message?.content || '';

    return {
      offerId: input.offerId,
      generatedAt: new Date().toISOString(),
      parties: {
        buyer: {
          name: input.buyer.full_name,
        },
        seller: {
          name: input.seller.full_name,
        },
      },
      property: {
        address: input.property.address,
        description: input.property.description || input.property.title,
        area_m2: input.property.area_m2,
      },
      terms: {
        agreedPrice: input.agreedPrice,
        currency: 'USD',
        paymentTerms: '10% deposit upon signing, balance at closing',
        conditions: [
          'Clear title verification',
          'Property inspection',
          'No outstanding liens or encumbrances',
          'Valid property registration',
        ],
      },
      content: contractContent,
      disclaimer: getLegalDisclaimer(),
    };
  } catch (error) {
    console.error('DeepSeek contract generation error:', error);

    // Return a template-based fallback
    const fallbackContent = generateFallbackContract(input);

    return {
      offerId: input.offerId,
      generatedAt: new Date().toISOString(),
      parties: {
        buyer: { name: input.buyer.full_name },
        seller: { name: input.seller.full_name },
      },
      property: {
        address: input.property.address,
        description: input.property.description || input.property.title,
        area_m2: input.property.area_m2,
      },
      terms: {
        agreedPrice: input.agreedPrice,
        currency: 'USD',
        paymentTerms: '10% deposit upon signing, balance at closing',
        conditions: [
          'Clear title verification',
          'Property inspection',
          'No outstanding liens or encumbrances',
        ],
      },
      content: fallbackContent,
      disclaimer: getLegalDisclaimer(),
    };
  }
}

function generateFallbackContract(input: ContractInput): string {
  const market = getMarketConfig();
  const today = new Date().toLocaleDateString(market.currency.locale, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `
═══════════════════════════════════════════════════════════════
                    BORRADOR DE CONTRATO DE COMPRAVENTA
                    DRAFT PURCHASE AGREEMENT
═══════════════════════════════════════════════════════════════

                    ⚠️ DOCUMENTO NO VINCULANTE ⚠️
                    ⚠️ NON-BINDING DOCUMENT ⚠️

Fecha / Date: ${today}
Referencia / Reference: ${input.offerId}

───────────────────────────────────────────────────────────────
                         PARTES / PARTIES
───────────────────────────────────────────────────────────────

VENDEDOR / SELLER:
Nombre / Name: ${input.seller.full_name}
Cédula / ID: [________________________]
Domicilio / Address: [________________________]

COMPRADOR / BUYER:
Nombre / Name: ${input.buyer.full_name}
Cédula / ID: [________________________]
Domicilio / Address: [________________________]

───────────────────────────────────────────────────────────────
                    DESCRIPCIÓN DEL INMUEBLE
                    PROPERTY DESCRIPTION
───────────────────────────────────────────────────────────────

Dirección / Address: ${input.property.address}
Descripción / Description: ${input.property.description || input.property.title}
Área / Area: ${input.property.area_m2 ? `${input.property.area_m2} m²` : '[A verificar / To be verified]'}
Tipo / Type: ${input.property.property_type}
Número de Registro / Registry Number: [________________________]

───────────────────────────────────────────────────────────────
                    TÉRMINOS DE LA TRANSACCIÓN
                    TRANSACTION TERMS
───────────────────────────────────────────────────────────────

PRECIO ACORDADO / AGREED PRICE:
$${input.agreedPrice.toLocaleString()} USD (Dólares de los Estados Unidos de América)

FORMA DE PAGO / PAYMENT TERMS:
1. Depósito inicial / Initial Deposit: $${Math.round(input.agreedPrice * 0.1).toLocaleString()} USD (10%)
   - Pagadero a la firma de este acuerdo preliminar
   - Payable upon signing of this preliminary agreement

2. Balance / Balance: $${Math.round(input.agreedPrice * 0.9).toLocaleString()} USD (90%)
   - Pagadero al cierre de la transacción
   - Payable at closing

FECHA ESTIMADA DE CIERRE / ESTIMATED CLOSING DATE:
[________________________] (Se sugieren 30-45 días / 30-45 days suggested)

───────────────────────────────────────────────────────────────
                         CONDICIONES
                         CONDITIONS
───────────────────────────────────────────────────────────────

1. El vendedor garantiza que el inmueble está libre de gravámenes,
   hipotecas y cualquier otro tipo de carga.
   The seller guarantees the property is free of liens, mortgages,
   and any other encumbrances.

2. El comprador tendrá derecho a realizar una inspección del
   inmueble antes del cierre.
   The buyer shall have the right to inspect the property
   before closing.

3. Ambas partes se comprometen a formalizar la venta ante notario
   público dentro del plazo establecido.
   Both parties agree to formalize the sale before a notary
   public within the established timeframe.

4. La transferencia de título se realizará ante el Registro de
   Títulos correspondiente.
   Title transfer shall be completed at the corresponding
   Title Registry Office.

───────────────────────────────────────────────────────────────
                          FIRMAS
                        SIGNATURES
───────────────────────────────────────────────────────────────

VENDEDOR / SELLER:

_________________________________
${input.seller.full_name}
Fecha / Date: ___________________


COMPRADOR / BUYER:

_________________________________
${input.buyer.full_name}
Fecha / Date: ___________________


TESTIGO / WITNESS:

_________________________________
Nombre / Name: ___________________
Cédula / ID: _____________________

═══════════════════════════════════════════════════════════════
              Generado por PriceMap / Generated by PriceMap
═══════════════════════════════════════════════════════════════
`.trim();
}

export async function generateOfferLetter(
  buyer: { full_name: string },
  seller: { full_name: string },
  property: { title: string; address: string; price: number },
  offerAmount: number,
  message?: string
): Promise<string> {
  const market = getMarketConfig();

  const prompt = `Generate a brief, professional offer letter in Spanish for a real estate offer in ${market.name}.

Buyer: ${buyer.full_name}
Seller: ${seller.full_name}
Property: ${property.title} at ${property.address}
Asking Price: ${formatPrice(property.price, market)}
Offer Amount: ${formatPrice(offerAmount, market)}
Buyer's Message: ${message || 'No additional message'}

Keep it concise (200-300 words), formal but friendly. Include:
1. Introduction and interest in the property
2. The offer amount and why it's reasonable
3. Proposed terms (standard: 10% deposit, 30-day closing)
4. Request for response

Write only the letter content, no headers or JSON.`;

  try {
    const response = await getClient().chat.completions.create({
      model: MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.4,
      max_tokens: 500,
    });

    return response.choices[0]?.message?.content || '';
  } catch (error) {
    console.error('DeepSeek offer letter error:', error);

    return `
Estimado/a ${seller.full_name},

Por medio de la presente, deseo expresar mi interés en adquirir la propiedad ubicada en ${property.address}.

Después de considerar cuidadosamente el valor de la propiedad y las condiciones actuales del mercado, me permito presentar una oferta formal de ${formatPrice(offerAmount, market)}.

${message ? `${message}\n\n` : ''}

Estoy preparado/a para proceder con los siguientes términos:
- Depósito inicial del 10% a la aceptación de esta oferta
- Cierre de la transacción dentro de 30 días
- Sujeto a verificación de título y condición del inmueble

Quedo a la espera de su respuesta favorable.

Atentamente,
${buyer.full_name}
    `.trim();
  }
}
