-- ============================================================================
-- DECISION PANELS V2 (Fairness Panel - Decision Intelligence)
-- ============================================================================
-- Main table for decision panel snapshots per offer
-- Each panel is a snapshot of the decision context at a specific moment
-- ============================================================================

CREATE TABLE IF NOT EXISTS pricewaze_decision_panels (
  offer_id UUID PRIMARY KEY REFERENCES pricewaze_offers(id) ON DELETE CASCADE,

  -- Panel states
  price_position TEXT NOT NULL CHECK (price_position IN ('inside_range', 'outside_range')),
  uncertainty_level TEXT NOT NULL CHECK (uncertainty_level IN ('low', 'medium', 'high')),
  wait_risk_level TEXT NOT NULL CHECK (wait_risk_level IN ('low', 'medium', 'high')),
  market_velocity TEXT NOT NULL CHECK (market_velocity IN ('stable', 'accelerating', 'decelerating')),
  market_pressure TEXT NOT NULL CHECK (market_pressure IN ('low', 'medium', 'high')),

  -- Panel content
  explanation_summary TEXT NOT NULL,  -- 1-2 sentences (copilot)
  option_act JSONB NOT NULL,          -- { pros: string[], cons: string[] }
  option_wait JSONB NOT NULL,          -- { pros: string[], cons: string[] }

  -- Personalization
  profile_applied TEXT CHECK (profile_applied IN ('buyer', 'investor', 'urgent', NULL)),
  model_version TEXT NOT NULL DEFAULT 'die-1.0',

  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_decision_panels_offer_id ON pricewaze_decision_panels(offer_id);
CREATE INDEX IF NOT EXISTS idx_decision_panels_created_at ON pricewaze_decision_panels(created_at DESC);

-- RLS Policies
ALTER TABLE pricewaze_decision_panels ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for idempotency)
DROP POLICY IF EXISTS "Participants can view decision panels" ON pricewaze_decision_panels;
DROP POLICY IF EXISTS "Participants can manage decision panels" ON pricewaze_decision_panels;
DROP POLICY IF EXISTS "Participants can update decision panels" ON pricewaze_decision_panels;

-- Participants can view decision panels for their offers
CREATE POLICY "Participants can view decision panels"
  ON pricewaze_decision_panels
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM pricewaze_offers o
      WHERE o.id = pricewaze_decision_panels.offer_id
      AND (o.buyer_id = auth.uid() OR o.seller_id = auth.uid())
    )
  );

-- Participants can insert/update decision panels for their offers
CREATE POLICY "Participants can manage decision panels"
  ON pricewaze_decision_panels
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM pricewaze_offers o
      WHERE o.id = pricewaze_decision_panels.offer_id
      AND (o.buyer_id = auth.uid() OR o.seller_id = auth.uid())
    )
  );

CREATE POLICY "Participants can update decision panels"
  ON pricewaze_decision_panels
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM pricewaze_offers o
      WHERE o.id = pricewaze_decision_panels.offer_id
      AND (o.buyer_id = auth.uid() OR o.seller_id = auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM pricewaze_offers o
      WHERE o.id = pricewaze_decision_panels.offer_id
      AND (o.buyer_id = auth.uid() OR o.seller_id = auth.uid())
    )
  );

-- Comments
COMMENT ON TABLE pricewaze_decision_panels IS 'Decision panel snapshots per offer. Each panel captures the decision context at a specific moment.';
COMMENT ON COLUMN pricewaze_decision_panels.price_position IS 'Price position: inside_range (within AVM range ± pressure) or outside_range';
COMMENT ON COLUMN pricewaze_decision_panels.uncertainty_level IS 'Uncertainty level: low (many comparables), medium (limited), high (scarce data)';
COMMENT ON COLUMN pricewaze_decision_panels.wait_risk_level IS 'Wait risk: low (low pressure + stable), medium (mixed), high (high pressure or acceleration)';
COMMENT ON COLUMN pricewaze_decision_panels.market_velocity IS 'Market velocity: stable (no changes), accelerating (activity increasing), decelerating (activity decreasing)';
COMMENT ON COLUMN pricewaze_decision_panels.market_pressure IS 'Market pressure: low (few visits), medium (visits or offers), high (multiple offers + confirmed signals)';
COMMENT ON COLUMN pricewaze_decision_panels.explanation_summary IS 'Executive summary of 1-2 sentences generated by the copilot';
COMMENT ON COLUMN pricewaze_decision_panels.option_act IS 'JSON with pros and cons of acting now: { pros: string[], cons: string[] }';
COMMENT ON COLUMN pricewaze_decision_panels.option_wait IS 'JSON with pros and cons of waiting: { pros: string[], cons: string[] }';
COMMENT ON COLUMN pricewaze_decision_panels.profile_applied IS 'Profile applied for personalization: buyer, investor, urgent, or NULL (generic)';
COMMENT ON COLUMN pricewaze_decision_panels.model_version IS 'DIE model version used to generate the panel';

